/*Copyright (c) 2022-2023 venturedive.com All Rights Reserved.
 This software is the confidential and proprietary information of venturedive.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with venturedive.com*/
package com.leave_management_system.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CavationDaysResponse implements Serializable {


    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("DAYS")
    private String days;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDays() {
        return this.days;
    }

    public void setDays(String days) {
        this.days = days;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CavationDaysResponse)) return false;
        final CavationDaysResponse cavationDaysResponse = (CavationDaysResponse) o;
        return Objects.equals(getName(), cavationDaysResponse.getName()) &&
                Objects.equals(getDays(), cavationDaysResponse.getDays());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName(),
                getDays());
    }
}