/*Copyright (c) 2022-2023 venturedive.com All Rights Reserved.
 This software is the confidential and proprietary information of venturedive.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with venturedive.com*/
package com.leave_management_system.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TobeApprovvedLeavesResponse implements Serializable {


    @ColumnAlias("FIRSTNAME")
    private String firstname;

    @ColumnAlias("LASTNAME")
    private String lastname;

    @ColumnAlias("PICURL")
    private String picurl;

    @ColumnAlias("BIRTHDATE")
    private Date birthdate;

    @ColumnAlias("JOB_TITLE")
    private String jobTitle;

    @ColumnAlias("CITY")
    private String city;

    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("START_DATE")
    private Date startDate;

    @ColumnAlias("END_DATE")
    private Date endDate;

    @ColumnAlias("EMP_ID")
    private BigInteger empId;

    @ColumnAlias("TENANT_ID")
    private BigInteger tenantId;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("TYPE")
    private String type;

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPicurl() {
        return this.picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public BigInteger getEmpId() {
        return this.empId;
    }

    public void setEmpId(BigInteger empId) {
        this.empId = empId;
    }

    public BigInteger getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(BigInteger tenantId) {
        this.tenantId = tenantId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TobeApprovvedLeavesResponse)) return false;
        final TobeApprovvedLeavesResponse tobeApprovvedLeavesResponse = (TobeApprovvedLeavesResponse) o;
        return Objects.equals(getFirstname(), tobeApprovvedLeavesResponse.getFirstname()) &&
                Objects.equals(getLastname(), tobeApprovvedLeavesResponse.getLastname()) &&
                Objects.equals(getPicurl(), tobeApprovvedLeavesResponse.getPicurl()) &&
                Objects.equals(getBirthdate(), tobeApprovvedLeavesResponse.getBirthdate()) &&
                Objects.equals(getJobTitle(), tobeApprovvedLeavesResponse.getJobTitle()) &&
                Objects.equals(getCity(), tobeApprovvedLeavesResponse.getCity()) &&
                Objects.equals(getId(), tobeApprovvedLeavesResponse.getId()) &&
                Objects.equals(getStartDate(), tobeApprovvedLeavesResponse.getStartDate()) &&
                Objects.equals(getEndDate(), tobeApprovvedLeavesResponse.getEndDate()) &&
                Objects.equals(getEmpId(), tobeApprovvedLeavesResponse.getEmpId()) &&
                Objects.equals(getTenantId(), tobeApprovvedLeavesResponse.getTenantId()) &&
                Objects.equals(getStatus(), tobeApprovvedLeavesResponse.getStatus()) &&
                Objects.equals(getType(), tobeApprovvedLeavesResponse.getType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFirstname(),
                getLastname(),
                getPicurl(),
                getBirthdate(),
                getJobTitle(),
                getCity(),
                getId(),
                getStartDate(),
                getEndDate(),
                getEmpId(),
                getTenantId(),
                getStatus(),
                getType());
    }
}