/*Copyright (c) 2022-2023 venturedive.com All Rights Reserved.
 This software is the confidential and proprietary information of venturedive.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with venturedive.com*/
package com.leave_management_system.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TotalLeavesYetResponse implements Serializable {


    @ColumnAlias("EMP_ID")
    private BigInteger empId;

    @ColumnAlias("C2")
    private BigInteger c2;

    public BigInteger getEmpId() {
        return this.empId;
    }

    public void setEmpId(BigInteger empId) {
        this.empId = empId;
    }

    public BigInteger getC2() {
        return this.c2;
    }

    public void setC2(BigInteger c2) {
        this.c2 = c2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TotalLeavesYetResponse)) return false;
        final TotalLeavesYetResponse totalLeavesYetResponse = (TotalLeavesYetResponse) o;
        return Objects.equals(getEmpId(), totalLeavesYetResponse.getEmpId()) &&
                Objects.equals(getC2(), totalLeavesYetResponse.getC2());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpId(),
                getC2());
    }
}