/*Copyright (c) 2022-2023 venturedive.com All Rights Reserved.
 This software is the confidential and proprietary information of venturedive.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with venturedive.com*/
package com.leave_management_system.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Vacationlist2Response implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("START_DATE")
    private Date startDate;

    @ColumnAlias("END_DATE")
    private Date endDate;

    @ColumnAlias("EMP_ID")
    private BigInteger empId;

    @ColumnAlias("TENANT_ID")
    private BigInteger tenantId;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("TYPE")
    private String type;

    @ColumnAlias("LEAVES_ALLOCATED")
    private BigInteger leavesAllocated;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public BigInteger getEmpId() {
        return this.empId;
    }

    public void setEmpId(BigInteger empId) {
        this.empId = empId;
    }

    public BigInteger getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(BigInteger tenantId) {
        this.tenantId = tenantId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public BigInteger getLeavesAllocated() {
        return this.leavesAllocated;
    }

    public void setLeavesAllocated(BigInteger leavesAllocated) {
        this.leavesAllocated = leavesAllocated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vacationlist2Response)) return false;
        final Vacationlist2Response vacationlist2response = (Vacationlist2Response) o;
        return Objects.equals(getId(), vacationlist2response.getId()) &&
                Objects.equals(getStartDate(), vacationlist2response.getStartDate()) &&
                Objects.equals(getEndDate(), vacationlist2response.getEndDate()) &&
                Objects.equals(getEmpId(), vacationlist2response.getEmpId()) &&
                Objects.equals(getTenantId(), vacationlist2response.getTenantId()) &&
                Objects.equals(getStatus(), vacationlist2response.getStatus()) &&
                Objects.equals(getType(), vacationlist2response.getType()) &&
                Objects.equals(getLeavesAllocated(), vacationlist2response.getLeavesAllocated());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getStartDate(),
                getEndDate(),
                getEmpId(),
                getTenantId(),
                getStatus(),
                getType(),
                getLeavesAllocated());
    }
}